spring.datasource.url=jdbc:mysql://localhost:3306/project_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
app.jwt.secret=${APP_JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidationInSpringBootApplication}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}